{
    "_Type": "Action.Type.ODataService.DraftEnabled.Save",
    "Target": {
        "Service": "/Cliente/Services/TestService.service",
        "EntitySet": "Cliente",
        "ReadLink": "{@odata.readLink}"
    },
    "ShowActivityIndicator": true,
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": {
        "Name": "/Cliente/Actions/UpdateEntitySuccessMessage.action",
        "Properties": {
            "Message": "Draft Saved"
        }
    },
    "OnFailure": "/Cliente/Actions/UpdateEntityFailureMessage.action"
}