{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "report",
        "Service": "/Equipment/Services/TestService.service",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "fecha": "#Control:fecha/#Value",
        "kilometraje_Horometro": "#Control:kilometraje_Horometro/#Value",
        "ubicacion": "#Control:ubicacion/#Value",
        "aceite_y_combustible": "#Control:aceite_y_combustible/#Value",
        "liquido_refrigerante": "#Control:liquido_refrigerante/#Value",
        "nivel_agua": "#Control:nivel_agua/#Value",
        "liquido_frenos": "#Control:liquido_frenos/#Value",
        "tapa_radiador_tanque": "#Control:tapa_radiador_tanque/#Value",
        "Cables_correas_mangueras": "#Control:Cables_correas_mangueras/#Value",
        "Bateria_cables_bornes": "#Control:Bateria_cables_bornes/#Value",
        "suspencion_gatos_muelles_anclajes": "#Control:suspencion_gatos_muelles_anclajes/#Value",
        "luces_bajas": "#Control:luces_bajas/#Value",
        "luces_altas": "#Control:luces_altas/#Value",
        "luces_internas": "#Control:luces_internas/#Value",
        "direccionales_frente": "#Control:direccionales_frente/#Value",
        "direccionales_atras": "#Control:direccionales_atras/#Value",
        "faros_freno": "#Control:faros_freno/#Value",
        "faros_exploradoras": "#Control:faros_exploradoras/#Value",
        "luces_parqueo": "#Control:luces_parqueo/#Value",
        "extintor": "#Control:extintor/#Value",
        "gato_cruceta_copa_perno": "#Control:gato_cruceta_copa_perno/#Value",
        "linterna_lamparas": "#Control:linterna_lamparas/#Value",
        "kit_herramientas_completa": "#Control:kit_herramientas_completa/#Value",
        "kit_derrames_completo": "#Control:kit_derrames_completo/#Value",
        "cables_arranque": "#Control:cables_arranque/#Value",
        "senalizacion": "#Control:senalizacion/#Value",
        "estado_llantas_rines": "#Control:estado_llantas_rines/#Value",
        "llantas_repuesto_fijas": "#Control:llantas_repuesto_fijas/#Value",
        "labrado_llantas": "#Control:labrado_llantas/#Value",
        "espejos_laterales": "#Control:espejos_laterales/#Value",
        "parabrisas_escobillas": "#Control:parabrisas_escobillas/#Value",
        "puertas_ventanas": "#Control:puertas_ventanas/#Value",
        "latoneria_pintura": "#Control:latoneria_pintura/#Value",
        "vidrios": "#Control:vidrios/#Value",
        "inyectores_agua_parabrisas": "#Control:inyectores_agua_parabrisas/#Value",
        "antena_gps_otros": "#Control:antena_gps_otros/#Value",
        "identificacion_carga": "#Control:identificacion_carga/#Value",
        "aire_acondicionado": "#Control:aire_acondicionado/#Value",
        "asientos_apoya_cabezas_tapiceria": "#Control:asientos_apoya_cabezas_tapiceria/#Value",
        "elevavidrios_manivelas": "#Control:elevavidrios_manivelas/#Value",
        "cinturones_seguridad": "#Control:cinturones_seguridad/#Value",
        "puertas": "#Control:puertas/#Value",
        "bocina_pito": "#Control:bocina_pito/#Value",
        "alarma_retroceso": "#Control:alarma_retroceso/#Value",
        "botiquin": "#Control:botiquin/#Value",
        "asa": "#Control:asa/#Value",
        "placas": "#Control:placas/#Value",
        "cuerpo": "#Control:cuerpo/#Value",
        "quijadas_laterales": "#Control:quijadas_laterales/#Value",
        "alineamiento": "#Control:alineamiento/#Value",
        "mantenimiento": "#Control:mantenimiento/#Value",
        "comentarios": "#Control:comentarios/#Value",
        "status": "#Control:status/#Value"
    },
    "UpdateLinks": [],
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": "/Equipment/Actions/UpdateEntitySuccessMessage.action",
    "OnFailure": "/Equipment/Actions/UpdateEntityFailureMessage.action"
}